package com.getlokalapp.paymentsdk.shared

import com.getlokalapp.paymentsdk.host.LokalGatewaySpmContributor
import com.getlokalapp.paymentsdk.host.LokalPaymentSdkSpmExtension
import com.getlokalapp.paymentsdk.host.SpmContribution
import org.gradle.api.Plugin
import org.gradle.api.Project
import java.io.File
import java.util.ServiceLoader

/**
 * The SPM-flavored sibling of `LokalPaymentPlugin`
 * (:gradle-plugins:cocoapods-host-plugin). A host applies EITHER this OR
 * `lokal-payment`, never both — see docs/cocoapods-to-spm-migration-plan.md (D5).
 * Applied to the module that declares the host's `XCFramework("<name>")` and
 * produces the umbrella framework.
 *
 * Generates `build/lokal/spmPackage/Package.swift`: a `binaryTarget` wrapping the
 * host's own XCFramework (named via [LokalPaymentSdkSpmExtension.xcFrameworkName]),
 * plus one `.package(url:, exact:)` dependency and product reference per
 * [LokalGatewaySpmContributor] contribution. A thin wrapper source target ties the
 * binary target and every vendor package's product together into the one product
 * the app depends on — a `binaryTarget` can't declare dependencies of its own, so
 * without this wrapper a vendor package would be listed but never actually linked.
 *
 * Regenerated on every Gradle sync (configuration phase, mirroring how
 * `SharedCocoapodsPlugin` regenerates the Podfile's managed regions). The app adds
 * the generated folder as a local Swift package **once**, by hand, in Xcode (File >
 * Add Package Dependencies > Add Local…): Xcode has no `pod install`-equivalent a
 * Gradle plugin can drive without editing `project.pbxproj` directly, which this SDK
 * deliberately avoids (see the plan doc's D2 rationale). Every regeneration after
 * that first manual step is picked up automatically — Xcode re-resolves a local
 * package's manifest on every build.
 */
class LokalPaymentSpmPlugin : Plugin<Project> {

    override fun apply(project: Project) {
        val config = project.extensions.create(
            "lokalPaymentSdkSpm",
            LokalPaymentSdkSpmExtension::class.java,
        )

        // afterEvaluate so contributors see the host's fully-declared dependency set
        // (their import self-gate), same timing as LokalPaymentPlugin.
        project.afterEvaluate {
            val xcFrameworkName = requireNotNull(config.xcFrameworkName) {
                "Host applies 'com.getlokalapp.paymentsdk.lokal-payment-spm' but has " +
                    "not set 'lokalPaymentSdkSpm { xcFrameworkName = \"...\" }' — " +
                    "required to locate the assembled .xcframework this plugin wraps."
            }
            val contributions = ServiceLoader.load(
                LokalGatewaySpmContributor::class.java,
                LokalGatewaySpmContributor::class.java.classLoader,
            ).mapNotNull { it.contribute(project, config) }

            writePackageSwift(project, xcFrameworkName, contributions)
        }
    }

    private fun writePackageSwift(
        project: Project,
        xcFrameworkName: String,
        contributions: List<SpmContribution>,
    ) {
        val packageDir = project.layout.buildDirectory.dir("lokal/spmPackage").get().asFile
        val umbrellaTargetName = "${xcFrameworkName}Umbrella"
        val sourcesDir = File(packageDir, "Sources/$umbrellaTargetName")
        sourcesDir.mkdirs()

        // A regular (non-binary) target needs at least one source file to exist;
        // this one carries no logic — its only job is to declare the dependencies
        // that tie the binary target and every vendor product into one product.
        writeIfChanged(
            File(sourcesDir, "Umbrella.swift"),
            "// GENERATED by the Lokal Payment SDK — do not edit.\n",
        )

        // KMP's XCFramework DSL assembles debug output under build/XCFrameworks/debug/
        // (confirmed empirically — see docs/cocoapods-to-spm-migration-plan.md Phase 0
        // Spike B). Release-configuration wiring is a follow-up, not yet handled here.
        val xcFrameworkDir = project.layout.buildDirectory
            .dir("XCFrameworks/debug/$xcFrameworkName.xcframework").get().asFile
        val xcFrameworkRelPath = packageDir.toPath().toAbsolutePath().normalize()
            .relativize(xcFrameworkDir.toPath().toAbsolutePath().normalize())
            .toString()

        val vendorPackages = contributions.map { it.vendorPackage }

        // Built as an explicit line list (mirroring SharedCocoapodsPlugin's Ruby
        // block generation) rather than a triple-quoted template with embedded
        // multi-line interpolation — trimIndent() can't reliably re-indent a block
        // whose own line count/content varies per host.
        val lines = mutableListOf(
            "// swift-tools-version:5.9",
            "// GENERATED by the Lokal Payment SDK — do not edit. Regenerated on every",
            "// Gradle sync; the app adds this folder as a local Swift package ONCE, by",
            "// hand, in Xcode (File > Add Package Dependencies > Add Local…) — see",
            "// docs/cocoapods-to-spm-migration-plan.md.",
            "import PackageDescription",
            "",
            "let package = Package(",
            "    name: \"$umbrellaTargetName\",",
            "    platforms: [.iOS(.v16)],",
            "    products: [",
            "        .library(name: \"$umbrellaTargetName\", targets: [\"$umbrellaTargetName\"]),",
            "    ],",
            "    dependencies: [",
        )
        vendorPackages.forEachIndexed { i, v ->
            val comma = if (i == vendorPackages.lastIndex) "" else ","
            lines += "        .package(url: \"${v.url}\", exact: \"${v.exactVersion}\")$comma"
        }
        lines += listOf(
            "    ],",
            "    targets: [",
            "        .binaryTarget(name: \"$xcFrameworkName\", path: \"$xcFrameworkRelPath\"),",
            "        .target(",
            "            name: \"$umbrellaTargetName\",",
            "            dependencies: [",
            "                \"$xcFrameworkName\",",
        )
        vendorPackages.forEachIndexed { i, v ->
            val comma = if (i == vendorPackages.lastIndex) "" else ","
            lines += "                .product(name: \"${v.productName}\", package: \"${v.packageName}\")$comma"
        }
        lines += listOf(
            "            ],",
            "            path: \"Sources/$umbrellaTargetName\"",
            "        ),",
            "    ]",
            ")",
        )

        writeIfChanged(File(packageDir, "Package.swift"), lines.joinToString("\n") + "\n")
    }

    private fun writeIfChanged(file: File, content: String) {
        if (!file.exists() || file.readText() != content) file.writeText(content)
    }
}
