import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kotlin.multiplatform.library)
    alias(libs.plugins.kotlin.serialization)
    id("org.jetbrains.kotlin.native.cocoapods")
    `maven-publish`
}

group = "com.getlokalapp.paymentsdk"

// Bakes this build's version (root gradle.properties) into commonMain as the
// constant behind LokalPaymentSdk.VERSION, so the runtime-visible SDK version
// can never drift from the published artifact version.
val generatePaymentSdkVersion by tasks.registering {
    val sdkVersion = version.toString()
    val outDir = layout.buildDirectory.dir("generated/paymentSdkVersion/kotlin")
    inputs.property("sdkVersion", sdkVersion)
    outputs.dir(outDir)
    doLast {
        val file = outDir.get().file("com/getlokalapp/paymentsdk/PaymentSdkVersion.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |package com.getlokalapp.paymentsdk
            |
            |// Generated by generatePaymentSdkVersion from the root
            |// gradle.properties' `version` — do not edit.
            |internal const val PAYMENT_SDK_VERSION: String = "$sdkVersion"
            |""".trimMargin(),
        )
    }
}

kotlin {
    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    androidLibrary {
        namespace = "com.getlokalapp.paymentsdk"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()

        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }

        withHostTest {}
    }

    iosX64()
    iosArm64()
    iosSimulatorArm64()

    cocoapods {
        version = project.version.toString()
        summary = "Lokal Payment SDK shared module"
        homepage = "https://github.com/getlokalapp/LokalPaymentSDK"
        ios.deploymentTarget = "16.0"
        name = "Shared"

        framework {
            baseName = "Shared"
            isStatic = true
        }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generatePaymentSdkVersion)
            dependencies {
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.serialization.json)
            }
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
        }
    }
}
