package com.getlokalapp.paymentsdk.cocoapods

import java.io.File

/**
 * Shared podspec-editing logic for the per-gateway `*-host-contributor`
 * modules. This source file is compiled into each contributor via a `srcDir` entry
 * (see their `build.gradle.kts`) rather than a published artifact, so every
 * contributor jar stays self-contained.
 */
internal object PodspecEditor {

    private const val MANAGED_COMMENT =
        "Generated by the Lokal Payment SDK — do not edit or remove."

    /**
     * Ensures the generated `podspec` declares `spec.dependency '<pod>', '<version>'`,
     * preceded by a managed [MANAGED_COMMENT] marker line so it's clear the entry is
     * SDK-owned and shouldn't be hand-edited.
     *
     * An existing declaration for [pod] — with any version or none, and its managed
     * comment if present — is rewritten to the pinned [version] rather than kept, so
     * it can't drift from the cinterop bindings the host consumes and the comment
     * never duplicates. If the pod is absent, the comment + line are appended before
     * the podspec's closing `end`. No write happens when the file already matches.
     */
    fun upsertPodDependency(podspec: File, pod: String, version: String) {
        if (!podspec.exists()) return
        val text = podspec.readText()
        val block = "    # $MANAGED_COMMENT\n    spec.dependency '$pod', '$version'"
        // Match an existing declaration for this pod (any version or none), plus an
        // immediately-preceding managed comment line if one is already there, so a
        // stale version — or an older comment — is rewritten rather than duplicated.
        val existing = Regex(
            "(?:^[ \\t]*#[^\\n]*Lokal Payment SDK[^\\n]*\\n)?" +
                "^[ \\t]*spec\\.dependency '${Regex.escape(pod)}'.*$",
            RegexOption.MULTILINE,
        )
        val updated = if (existing.containsMatchIn(text)) {
            existing.replace(text, Regex.escapeReplacement(block))
        } else {
            // Insert before the podspec's closing `end`.
            val at = text.lastIndexOf("\nend")
            if (at < 0) return
            text.substring(0, at) + "\n" + block + text.substring(at)
        }
        if (updated != text) podspec.writeText(updated)
    }
}
