package com.getlokalapp.paymentsdk.buildsrc

import org.gradle.api.DefaultTask
import org.gradle.api.Project
import org.gradle.api.tasks.TaskProvider
import org.gradle.kotlin.dsl.register

/**
 * Module-unique prefix for generated file names ("razorpay-checkout" →
 * "RazorpayCheckout"). Kotlin derives the JVM file-facade class name from
 * package + file name, so two modules generating an identically named file
 * into the same package (both razorpay modules share
 * com.getlokalapp.paymentsdk.razorpay) would ship colliding
 * `*Kt` classes and break any app that includes both AARs.
 */
private val Project.generatedFilePrefix: String
    get() = name.split('-', '_').joinToString("") { it.replaceFirstChar(Char::uppercaseChar) }

/**
 * Registers a task that bakes this project's own version (root
 * gradle.properties, via [Project.getVersion]) into
 * `internal const val $constName: String` inside [packageName] — so a
 * runtime-visible version constant can never drift from the published
 * artifact version. Used for :shared's PAYMENT_SDK_VERSION and every gateway
 * module's MODULE_VERSION (see GatewayMetadata.moduleVersion). Wire the
 * returned task into the relevant source set via `kotlin.srcDir(...)`.
 */
fun Project.registerModuleVersionTask(
    taskName: String,
    packageName: String,
    constName: String = "MODULE_VERSION",
): TaskProvider<DefaultTask> {
    val moduleVersion = project.version.toString()
    val filePrefix = generatedFilePrefix
    val outDir = layout.buildDirectory.dir("generated/$taskName/kotlin")
    return tasks.register<DefaultTask>(taskName) {
        inputs.property("moduleVersion", moduleVersion)
        outputs.dir(outDir)
        doLast {
            outDir.get().asFile.deleteRecursively()
            val file = outDir.get().file("${packageName.replace('.', '/')}/${filePrefix}ModuleVersion.kt").asFile
            file.parentFile.mkdirs()
            file.writeText(
                """
                |package $packageName
                |
                |// Generated by $taskName from this module's project version —
                |// do not edit.
                |internal const val $constName: String = "$moduleVersion"
                |""".trimMargin(),
            )
        }
    }
}

/**
 * Registers a task that bakes this host-contributor's owning gateway module name into
 * `internal const val OWNED_MODULE: String` inside [packageName]. The name is the parent
 * Gradle project's name (`:gateways:razorpay-checkout:host-contributor` →
 * `razorpay-checkout`), which — with the gateway modules publishing under group
 * `com.getlokalapp.paymentsdk` and no custom `artifactId` — equals the artifactId a host
 * declares and the umbrella plugins gate on. So a contributor's `module` (its
 * `LokalGatewayHostContributor`/`LokalGatewayHostAndroidContributor` identity) can't drift
 * from the gateway module it actually owns. Wire the returned task into the source set via
 * `kotlin.srcDir(...)`.
 */
fun Project.registerOwnedModuleTask(
    taskName: String,
    packageName: String,
): TaskProvider<DefaultTask> {
    val ownedModule = project.parent?.name
        ?: error("$path has no parent gateway project to derive the owned module name from")
    val filePrefix = generatedFilePrefix
    val outDir = layout.buildDirectory.dir("generated/$taskName/kotlin")
    return tasks.register<DefaultTask>(taskName) {
        inputs.property("ownedModule", ownedModule)
        outputs.dir(outDir)
        doLast {
            outDir.get().asFile.deleteRecursively()
            val file = outDir.get().file("${packageName.replace('.', '/')}/${filePrefix}OwnedModule.kt").asFile
            file.parentFile.mkdirs()
            file.writeText(
                """
                |package $packageName
                |
                |// Generated by $taskName from this contributor's parent gateway module
                |// name — do not edit.
                |internal const val OWNED_MODULE: String = "$ownedModule"
                |""".trimMargin(),
            )
        }
    }
}

/**
 * Registers a task that bakes [vendorSdkVersion] into a `VENDOR_SDK_VERSION`
 * constant inside [packageName] (see GatewayMetadata.vendorSdkVersion). Set
 * [asActual] when the gateway module declares
 * `internal expect val VENDOR_SDK_VERSION: String` in commonMain
 * (multi-platform gateways, where the version differs by platform — call
 * this once per platform, each with its own [taskName]); leave it false for
 * a single-platform gateway module, where a bare `const val` is enough.
 */
fun Project.registerVendorVersionTask(
    taskName: String,
    packageName: String,
    vendorSdkVersion: String,
    asActual: Boolean = true,
): TaskProvider<DefaultTask> {
    val filePrefix = generatedFilePrefix
    val outDir = layout.buildDirectory.dir("generated/$taskName/kotlin")
    return tasks.register<DefaultTask>(taskName) {
        inputs.property("vendorSdkVersion", vendorSdkVersion)
        outputs.dir(outDir)
        doLast {
            outDir.get().asFile.deleteRecursively()
            val file = outDir.get().file("${packageName.replace('.', '/')}/${filePrefix}VendorSdkVersion.kt").asFile
            file.parentFile.mkdirs()
            val modifier = if (asActual) "actual" else "const"
            file.writeText(
                """
                |package $packageName
                |
                |// Generated by $taskName — do not edit.
                |internal $modifier val VENDOR_SDK_VERSION: String = "$vendorSdkVersion"
                |""".trimMargin(),
            )
        }
    }
}
