package com.getlokalapp.paymentsdk.juspay.host

import com.getlokalapp.paymentsdk.cocoapods.PodspecEditor
import com.getlokalapp.paymentsdk.host.LokalGatewayHostContributor
import com.getlokalapp.paymentsdk.host.LokalPaymentSdkExtension
import com.getlokalapp.paymentsdk.host.LokalPostInstallSnippets
import org.gradle.api.Project

/**
 * Juspay's build-time contribution to an iOS host: appends `spec.dependency 'HyperSDK'`
 * to the host module's generated podspec so the vendor pod is pulled transitively from
 * the CocoaPods trunk — the host never names HyperSDK in its Podfile. Discovered by the
 * umbrella `com.getlokalapp.paymentsdk.lokal-payment` plugin via ServiceLoader, exactly
 * like Razorpay's contributor — so a host applies only `lokal-payment` on its iOS
 * module, nothing Juspay-specific.
 *
 * Self-gates on the host actually depending on :juspay. This jar is always on the
 * buildscript classpath (the umbrella depends on it), so "Juspay not used" is an early
 * return: nothing is added to the podspec and no HyperSDK pod is linked unless :juspay
 * is imported.
 *
 * This is only the **iOS** half of Juspay's host wiring. The Android half (applying
 * `hypersdk.plugin` + forwarding the client id) lives in the separate
 * `com.getlokalapp.paymentsdk.juspay-android-host` plugin, applied on the host's
 * `com.android.application` module — it can't fold in here, because that work must run
 * eagerly on the application module, which this umbrella-dispatched, afterEvaluate
 * contributor is the wrong phase/module for.
 *
 * Deliberately does NOT add a `pod(...)` cinterop to the host module: the Kotlin
 * bindings already ride in via the published :juspay klib (Maven), and a cinterop here
 * would drag the host's iOS compile through HyperSDK's synthetic-build "Validate
 * Mandatory Files" gate. The `MerchantConfig.txt` HyperSDK's asset pipeline reads is
 * generated by this contributor (see [writeMerchantConfig]), from the same
 * [CLIENT_ID_PROPERTY] gradle property the Android host plugin forwards into
 * `hypersdk.plugin`, so a host declares its Juspay clientId exactly once. The asset
 * pipeline itself (`Pods/HyperSDK/Fuse.rb`, run after `pod install`) is triggered by a
 * small Ruby snippet this contributor drops in `build/lokal/postInstall/juspay.rb`
 * (see [writePostInstallSnippet]) — never a raw `post_install` block in the host's
 * Podfile, because CocoaPods' `post_install` hook doesn't chain: a second one would
 * silently replace the first. `SharedCocoapodsPlugin` owns the single managed
 * `post_install` block that discovers and runs this file (see
 * [com.getlokalapp.paymentsdk.host.LokalPostInstallSnippets]).
 */
class JuspayHostContributor : LokalGatewayHostContributor {

    override fun contribute(target: Project, config: LokalPaymentSdkExtension) {
        val importsJuspay = target.configurations
            .flatMap { it.dependencies }
            .any { it.group == SDK_GROUP && it.name == JUSPAY_MODULE }
        if (!importsJuspay) return

        // The host module applies `org.jetbrains.kotlin.native.cocoapods`, which
        // registers the `podspec` task that generates `<name>.podspec`. Hook its
        // doLast so every regeneration re-adds our transitive dependency — the
        // generator rewrites the file from scratch each run, so this can't be a
        // one-time edit.
        target.plugins.withId("org.jetbrains.kotlin.native.cocoapods") {
            target.tasks.named("podspec").configure { task ->
                task.doLast {
                    PodspecEditor.upsertPodDependency(
                        podspec = target.file("${target.name}.podspec"),
                        pod = "HyperSDK",
                        // VENDOR_SDK_VERSION is generated from libs.versions.toml's
                        // juspay-pod-ios entry (see build.gradle.kts).
                        version = VENDOR_SDK_VERSION,
                    )
                }
            }
        }

        writeMerchantConfig(target)
        writePostInstallSnippet(target)
    }

    /**
     * Writes `iosApp/MerchantConfig.txt` from [CLIENT_ID_PROPERTY], the same gradle
     * property [com.getlokalapp.paymentsdk.juspay.host.JuspayAndroidHostPlugin] forwards
     * into `hypersdk.plugin` on the Android side — so the host's Juspay clientId lives in
     * exactly one place instead of two independently-maintained files that can drift out
     * of sync. Runs eagerly (this whole method executes inside the umbrella plugin's
     * `afterEvaluate`, same as [PodspecEditor]'s caller), so it's current on every Gradle
     * configuration — in particular the one the Podfile's own bootstrap block triggers at
     * Podfile-evaluation time, well before `post_install`'s `Fuse.rb` step needs the file.
     *
     * Fails loudly if `:juspay` is imported but [CLIENT_ID_PROPERTY] isn't set, mirroring
     * `hypersdk.plugin`'s own hard failure on an unregistered clientId — a missing property
     * would otherwise surface much later as a confusing native asset-download failure.
     */
    private fun writeMerchantConfig(target: Project) {
        val clientId = target.providers.gradleProperty(CLIENT_ID_PROPERTY).orNull
        checkNotNull(clientId) {
            "Host imports :juspay but has not set the '$CLIENT_ID_PROPERTY' gradle property " +
                "(gradle.properties, or -P/ORG_GRADLE_PROJECT_…) — required to generate " +
                "iosApp/MerchantConfig.txt for HyperSDK's merchant asset download."
        }
        target.file("../iosApp/MerchantConfig.txt").writeText(
            "# Generated by the Lokal Payment SDK from the '$CLIENT_ID_PROPERTY' gradle " +
                "property — do not edit.\n" +
                "clientId = $clientId\n",
        )
    }

    /**
     * Drops `build/lokal/postInstall/juspay.rb` — the exact `post_install` body Juspay's
     * docs prescribe (kept verbatim, just relocated), run by `SharedCocoapodsPlugin`'s one
     * managed `post_install` block instead of a Juspay-owned one (see
     * [com.getlokalapp.paymentsdk.host.LokalPostInstallSnippets] for why). `installer` is in
     * scope when this is `eval`'d even though this particular snippet doesn't need it —
     * Fuse.rb resolves `Pods/HyperSDK` off the working directory, which is `iosApp/` both
     * for a real `post_install do |installer| ... end` and for this `eval`'d equivalent.
     */
    private fun writePostInstallSnippet(target: Project) {
        val dir = target.layout.buildDirectory.dir(LokalPostInstallSnippets.BUILD_RELATIVE_DIR).get().asFile
        dir.mkdirs()
        dir.resolve("juspay.rb").writeText(
            """
            # Generated by the Lokal Payment SDK — do not edit. Juspay's merchant-asset
            # pipeline: downloads/places assets for the clientId in MerchantConfig.txt.
            # Without this, HyperSDK's "[CP-User] Validate Mandatory Files" build phase
            # fails the app build.
            fuse_path = "./Pods/HyperSDK/Fuse.rb"
            clean_assets = false # pass true to force re-downloading all assets
            if File.exist?(fuse_path)
              system("ruby", fuse_path.to_s, clean_assets.to_s)
            end
            """.trimIndent() + "\n",
        )
    }

    private companion object {
        const val SDK_GROUP = "com.getlokalapp.paymentsdk"
        const val JUSPAY_MODULE = "juspay"

        // Same gradle property JuspayAndroidHostPlugin reads — one host-declared value
        // shared across both platforms.
        const val CLIENT_ID_PROPERTY = "juspayClientId"
    }
}
