[versions]
agp = "9.2.1"
kotlin = "2.4.0"
android-compileSdk = "37"
android-minSdk = "24"
android-targetSdk = "37"

androidx-activityCompose = "1.13.0"
androidx-appcompat = "1.7.1"
composeMultiplatform = "1.11.1"
kotlinxCoroutines = "1.11.0"
kotlinxSerialization = "1.11.0"

lokalPaymentSdk = "0.0.1"

[libraries]

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
lokalpaymentsdk-lokal-payment-android = { id = "com.getlokalapp.paymentsdk.lokal-payment-android", version.ref = "lokalPaymentSdk" }
lokalpaymentsdk-lokal-payment = { id = "com.getlokalapp.paymentsdk.lokal-payment", version.ref = "lokalPaymentSdk" }
