package com.getlokalapp.paymentsdk.shared

import com.getlokalapp.paymentsdk.host.HostContribution
import com.getlokalapp.paymentsdk.host.LokalPaymentSdkExtension
import org.gradle.api.Project
import java.io.File

/**
 * Writes `INTEGRATION.md` beside the generated `Package.swift` — the app-specific,
 * regenerated-every-sync onboarding steps for THIS host's actual gateway selection: the
 * local-package path, the product to link vs. the module to `import` (deliberately
 * different names), the rebuild task, ready-to-paste XcodeGen/Tuist wiring, and any
 * per-gateway one-time steps contributed via [HostContribution.consumerNotes] (e.g.
 * Juspay's scheme pre-build action). The durable, hand-maintained companion is
 * docs/integrating-the-sdk.md; this file is the machine-generated, always-current view.
 * The lifecycle pointer is logged only when the file actually changes (e.g. a gateway was
 * added or removed) so a plain rebuild stays quiet.
 */
internal fun writeIntegrationNotes(
    project: Project,
    config: LokalPaymentSdkExtension,
    xcFrameworkName: String,
    umbrellaTargetName: String,
    contributions: List<HostContribution>,
    queriesSchemes: List<String>,
    plistPatched: Boolean,
    xcodeProjectWired: Boolean,
    prebuildScript: File?,
) {
    val packageDir = project.layout.buildDirectory.dir("lokal/spmPackage").get().asFile
    val assembleTask = "${project.path}:assemble${xcFrameworkName}ReleaseXCFramework"
    val packageAbsPath = packageDir.toPath().toAbsolutePath().normalize().toString()
    val notes = contributions.flatMap { it.consumerNotes }

    val md = mutableListOf(
        "# Integrating $umbrellaTargetName into your iOS app",
        "",
        "GENERATED by the Lokal Payment SDK — regenerated on every Gradle sync. Do not",
        "edit; changes are overwritten. It reflects *this* module's current gateway",
        "selection. Full hand-written guide: LokalPaymentSDK/docs/integrating-the-sdk.md",
        "",
        "## The names you need",
        "",
        "| Thing | Value |",
        "| --- | --- |",
        "| Local Swift package | `$packageAbsPath` |",
        "| Product to link | `$umbrellaTargetName` |",
        "| Swift import | `import $xcFrameworkName` |",
        "",
        "The product and the import differ on purpose: link the **$umbrellaTargetName**",
        "product, but write `import $xcFrameworkName` to call the SDK's API.",
        "",
        "## 1. Rebuild after any Kotlin change",
        "",
        "```",
        "./gradlew $assembleTask",
        "```",
        "",
        "SPM binary targets are prebuilt, so there is no per-Xcode-build Gradle step —",
        "re-run this whenever you change Kotlin, then build in Xcode as usual.",
    )

    // Section 2 mirrors the Info.plist note's two-branch shape: when the host set
    // `iosXcodeProject`, the package is wired for them and there's nothing to do by hand;
    // otherwise surface the manual "Add Local…" wiring — and the opt-in that automates it.
    md += ""
    md += "## 2. Add the local package (one-time)"
    md += ""
    if (xcodeProjectWired) {
        md += "The SDK wires this local package into the `.xcodeproj` you pointed"
        md += "`lokalPaymentSdk { iosXcodeProject = … }` at, on every Gradle sync — the"
        md += "`$umbrellaTargetName` product is added as a package product dependency for you."
        md += "The edit is idempotent (a project already wired is left untouched), so there is"
        md += "nothing to do by hand."
    } else {
        md += "Point your project at the package folder above. In a committed spec, use a path"
        md += "relative to the spec file (the demo uses `../composeApp/build/lokal/spmPackage`)."
        md += ""
        md += "### XcodeGen — project.yml"
        md += ""
        md += "```yaml"
        md += "packages:"
        md += "  $xcFrameworkName:"
        md += "    path: <relative-path-to>/build/lokal/spmPackage"
        md += "targets:"
        md += "  YourApp:"
        md += "    dependencies:"
        md += "      - package: $xcFrameworkName"
        md += "        product: $umbrellaTargetName"
        md += "```"
        md += ""
        md += "### Tuist — Project.swift"
        md += ""
        md += "```swift"
        md += "let project = Project("
        md += "    name: \"YourApp\","
        md += "    packages: [.local(path: \"<relative-path-to>/build/lokal/spmPackage\")],"
        md += "    targets: ["
        md += "        .target("
        md += "            name: \"YourApp\","
        md += "            // …"
        md += "            dependencies: [.package(product: \"$umbrellaTargetName\")]"
        md += "        ),"
        md += "    ]"
        md += ")"
        md += "```"
        md += ""
        md += "### Hand-managed .xcodeproj (Xcode's \"Add Local…\")"
        md += ""
        md += "*File ▸ Add Package Dependencies… ▸ Add Local…* → select the package folder"
        md += "above, then add the **$umbrellaTargetName** product to your app target. Or set"
        md += "`lokalPaymentSdk { iosXcodeProject = \"<path-to>.xcodeproj\" }` and the SDK does"
        md += "this for you on every sync (hand-managed `.xcodeproj` only — not XcodeGen/Tuist,"
        md += "which own their generated project)."
    }
    md += ""
    md += "## 3. Import and use"
    md += ""
    md += "```swift"
    md += "import $xcFrameworkName"
    md += "```"
    if (queriesSchemes.isNotEmpty()) {
        md += ""
        md += "## 4. Info.plist — UPI query schemes"
        md += ""
        if (plistPatched) {
            val plistPath = project.file(config.iosInfoPlist!!)
                .toPath().toAbsolutePath().normalize().toString()
            md += "The SDK keeps `LSApplicationQueriesSchemes` in your `Info.plist` up to"
            md += "date on every Gradle sync (needed for `canOpenURL` UPI-app detection):"
            md += ""
            md += "`$plistPath`"
            md += ""
            md += "The merge is idempotent — it only adds schemes that aren't already there,"
            md += "and never touches your other entries. Nothing to do by hand."
        } else {
            md += "Add these schemes to `LSApplicationQueriesSchemes` in your app's"
            md += "`Info.plist` so `canOpenURL` can detect installed UPI apps:"
            md += ""
            md += "```xml"
            md += "<key>LSApplicationQueriesSchemes</key>"
            md += "<array>"
            queriesSchemes.forEach { md += "    <string>$it</string>" }
            md += "</array>"
            md += "```"
            md += ""
            md += "Or set `lokalPaymentSdk { iosInfoPlist = \"<path-to>/Info.plist\" }` and the"
            md += "SDK will merge them for you on every sync."
        }
    }
    if (prebuildScript != null) {
        md += ""
        md += "## 5. Xcode pre-build action (one-time)"
        md += ""
        md += "One or more gateways run a script before each Xcode build (e.g. Juspay's"
        md += "HyperSDK asset download). Register it **once** as a scheme pre-build action —"
        md += "new gateways plug into the same action, so you never edit this again:"
        md += ""
        md += "1. Xcode → Product → Scheme → Edit Scheme → Build → Pre-actions → **+** →"
        md += "   New Run Script Action."
        md += "2. Set **Provide build settings from** to your app target (so `\$BUILD_DIR` and"
        md += "   friends are in scope for the script)."
        md += "3. Script body:"
        md += ""
        md += "```sh"
        md += "\"${prebuildScript.toPath().toAbsolutePath().normalize()}\""
        md += "```"
        md += ""
        md += "In a committed XcodeGen/Tuist spec, reference the script by a path relative to"
        md += "the spec rather than the absolute one above."
    }
    if (notes.isNotEmpty()) {
        md += ""
        md += "## 6. Gateway-specific one-time setup"
        md += ""
        md += "Only the gateways this module enabled appear here."
        notes.forEach { note ->
            md += ""
            md += "### ${note.heading}"
            md += ""
            note.steps.forEach { step -> md += "- $step" }
        }
    }

    val integrationFile = File(packageDir, "INTEGRATION.md")
    val changed = writeIfChanged(integrationFile, md.joinToString("\n") + "\n")
    if (changed) {
        project.logger.lifecycle("LokalPaymentSDK: iOS integration steps updated → $integrationFile")
    }
}
