package com.getlokalapp.paymentsdk.shared

import com.getlokalapp.paymentsdk.host.HostContribution
import com.getlokalapp.paymentsdk.host.LokalPaymentSdkExtension
import org.gradle.api.Project
import java.io.File

/**
 * Writes `INTEGRATION.md` beside the generated `Package.swift` — the app-specific,
 * regenerated-every-sync onboarding steps for THIS host's actual gateway selection: the
 * local-package path, the product to link vs. the module to `import` (deliberately
 * different names), the rebuild task, ready-to-paste XcodeGen/Tuist wiring, and any
 * per-gateway one-time steps contributed via [HostContribution.consumerNotes] (e.g.
 * Juspay's scheme pre-build action). The durable, hand-maintained companion is
 * docs/integrating-the-sdk.md; this file is the machine-generated, always-current view.
 * The lifecycle pointer is logged only when the file actually changes (e.g. a gateway was
 * added or removed) so a plain rebuild stays quiet.
 */
internal fun writeIntegrationNotes(
    project: Project,
    config: LokalPaymentSdkExtension,
    xcFrameworkName: String,
    umbrellaTargetName: String,
    contributions: List<HostContribution>,
    queriesSchemes: List<String>,
    plistPatched: Boolean,
    xcodeProjectWired: Boolean,
    prebuildScript: File?,
    bundledResources: List<String> = emptyList(),
    schemeWired: Boolean = false,
) {
    val packageDir = project.layout.buildDirectory.dir("lokal/spmPackage").get().asFile
    val bootstrapTask = "${project.path}:${STAGE_TASK_BASE}Debug"
    val packageAbsPath = packageDir.toPath().toAbsolutePath().normalize().toString()
    val notes = contributions.flatMap { it.consumerNotes }

    val md = mutableListOf(
        "# Integrating $umbrellaTargetName into your iOS app",
        "",
        "GENERATED by the Lokal Payment SDK — regenerated on every Gradle sync. Do not",
        "edit; changes are overwritten. It reflects *this* module's current gateway",
        "selection. Full hand-written guide: LokalPaymentSDK/docs/integrating-the-sdk.md",
        "",
        "## The names you need",
        "",
        "| Thing | Value |",
        "| --- | --- |",
        "| Local Swift package | `$packageAbsPath` |",
        "| Product to link | `$umbrellaTargetName` |",
        "| Swift import | `import $xcFrameworkName` |",
        "",
        "The product and the import differ on purpose: link the **$umbrellaTargetName**",
        "product, but write `import $xcFrameworkName` to call the SDK's API.",
        "",
        "## 1. Bootstrap the Kotlin binary (one-time, after cloning)",
        "",
        "```",
        "./gradlew $bootstrapTask",
        "```",
        "",
        "Kotlin changes are picked up automatically from then on: the pre-build action in §5",
        "reassembles and restages the XCFramework on every Xcode build, choosing the **debug**",
        "Kotlin binary for Debug configurations and the **release** one for everything else. You",
        "do not re-run Gradle by hand after editing Kotlin.",
        "",
        "This one command is still needed first because SwiftPM validates the binary target's",
        "path while *resolving* the package graph — which happens before any pre-action can run,",
        "so the very first resolve needs an already-assembled artifact. It builds the debug",
        "variant deliberately: it links far faster than release.",
        "",
        "Set `LOKAL_SKIP_KOTLIN_ASSEMBLE=1` to suppress the per-build Gradle invocation (for CI",
        "that assembles the XCFramework itself before invoking `xcodebuild`).",
    )

    // Section 2 mirrors the Info.plist note's two-branch shape: when the host set
    // `iosXcodeProject`, the package is wired for them and there's nothing to do by hand;
    // otherwise surface the manual "Add Local…" wiring — and the opt-in that automates it.
    md += ""
    md += "## 2. Add the local package (one-time)"
    md += ""
    if (xcodeProjectWired) {
        md += "The SDK wires this local package into the `.xcodeproj` you pointed"
        md += "`lokalPaymentSdk { iosXcodeProject = … }` at, on every Gradle sync — the"
        md += "`$umbrellaTargetName` product is added as a package product dependency for you."
        md += "The edit is idempotent (a project already wired is left untouched), so there is"
        md += "nothing to do by hand."
    } else {
        md += "Point your project at the package folder above. In a committed spec, use a path"
        md += "relative to the spec file (the demo uses `../composeApp/build/lokal/spmPackage`)."
        md += ""
        md += "### XcodeGen — project.yml"
        md += ""
        md += "```yaml"
        md += "packages:"
        md += "  $xcFrameworkName:"
        md += "    path: <relative-path-to>/build/lokal/spmPackage"
        md += "targets:"
        md += "  YourApp:"
        md += "    dependencies:"
        md += "      - package: $xcFrameworkName"
        md += "        product: $umbrellaTargetName"
        md += "```"
        md += ""
        md += "### Tuist — Project.swift"
        md += ""
        md += "```swift"
        md += "let project = Project("
        md += "    name: \"YourApp\","
        md += "    packages: [.local(path: \"<relative-path-to>/build/lokal/spmPackage\")],"
        md += "    targets: ["
        md += "        .target("
        md += "            name: \"YourApp\","
        md += "            // …"
        md += "            dependencies: [.package(product: \"$umbrellaTargetName\")]"
        md += "        ),"
        md += "    ]"
        md += ")"
        md += "```"
        md += ""
        md += "### Hand-managed .xcodeproj (Xcode's \"Add Local…\")"
        md += ""
        md += "*File ▸ Add Package Dependencies… ▸ Add Local…* → select the package folder"
        md += "above, then add the **$umbrellaTargetName** product to your app target. Or set"
        md += "`lokalPaymentSdk { iosXcodeProject = \"<path-to>.xcodeproj\" }` and the SDK does"
        md += "this for you on every sync (hand-managed `.xcodeproj` only — not XcodeGen/Tuist,"
        md += "which own their generated project)."
    }
    md += ""
    md += "## 3. Import and use"
    md += ""
    md += "```swift"
    md += "import $xcFrameworkName"
    md += "```"
    if (queriesSchemes.isNotEmpty()) {
        md += ""
        md += "## 4. Info.plist — UPI query schemes"
        md += ""
        if (plistPatched) {
            val plistPath = project.file(config.iosInfoPlist!!)
                .toPath().toAbsolutePath().normalize().toString()
            md += "The SDK keeps `LSApplicationQueriesSchemes` in your `Info.plist` up to"
            md += "date on every Gradle sync (needed for `canOpenURL` UPI-app detection):"
            md += ""
            md += "`$plistPath`"
            md += ""
            md += "The merge is idempotent — it only adds schemes that aren't already there,"
            md += "and never touches your other entries. Nothing to do by hand."
        } else {
            md += "Add these schemes to `LSApplicationQueriesSchemes` in your app's"
            md += "`Info.plist` so `canOpenURL` can detect installed UPI apps:"
            md += ""
            md += "```xml"
            md += "<key>LSApplicationQueriesSchemes</key>"
            md += "<array>"
            queriesSchemes.forEach { md += "    <string>$it</string>" }
            md += "</array>"
            md += "```"
            md += ""
            md += "Or set `lokalPaymentSdk { iosInfoPlist = \"<path-to>/Info.plist\" }` and the"
            md += "SDK will merge them for you on every sync."
        }
    }
    if (prebuildScript != null) {
        md += ""
        md += "## 5. Xcode pre-build action"
        md += ""
        if (schemeWired) {
            md += "Already done for you — nothing to do here."
            md += ""
            md += "The SDK registers the dispatcher below as a build pre-action on every Gradle"
            md += "sync, in the scheme you pointed `lokalPaymentSdk { iosXcodeScheme }` at, and"
            md += "leaves it alone once it is there. New gateways plug into the same action."
            md += ""
            md += "```sh"
            md += "\"${prebuildScript.toPath().toAbsolutePath().normalize()}\""
            md += "```"
        } else {
            md += "This action restages the Kotlin binary on every build, and runs whatever"
            md += "build-time steps your gateways need (e.g. Juspay's HyperSDK asset download)."
            md += "**Skip it and Xcode builds against a stale Kotlin framework.** Register it"
            md += "**once** — new gateways plug into the same action, so you never edit it again:"
            md += ""
            md += "1. Xcode → Product → Scheme → Edit Scheme → Build → Pre-actions → **+** →"
            md += "   New Run Script Action."
            md += "2. Set **Provide build settings from** to your app target (so `\$CONFIGURATION`"
            md += "   and friends are in scope for the script)."
            md += "3. Script body:"
            md += ""
            md += "```sh"
            md += "\"${prebuildScript.toPath().toAbsolutePath().normalize()}\""
            md += "```"
            md += ""
            md += "In a committed XcodeGen/Tuist spec, reference the script by a path relative to"
            md += "the spec rather than the absolute one above. For a hand-managed `.xcodeproj`,"
            md += "set `lokalPaymentSdk { iosXcodeScheme = \"<path-to>.xcscheme\" }` and the SDK"
            md += "will register it for you on every sync."
        }
    }
    if (notes.isNotEmpty()) {
        md += ""
        md += "## 6. Gateway-specific one-time setup"
        md += ""
        md += "Only the gateways this module enabled appear here."
        notes.forEach { note ->
            md += ""
            md += "### ${note.heading}"
            md += ""
            note.steps.forEach { step -> md += "- $step" }
        }
    }
    // Bundled resources: files an active gateway generated that must ship INSIDE the .app.
    // Rendered last because whether anything is required of the reader depends on the same
    // iosXcodeProject opt-in as section 2 — when set, this is purely informational.
    if (bundledResources.isNotEmpty()) {
        md += ""
        md += "## 7. Bundled resources"
        md += ""
        if (xcodeProjectWired) {
            md += "These files are generated by the SDK and added to your app target's Resources"
            md += "build phase for you on every Gradle sync, in the `.xcodeproj` you pointed"
            md += "`lokalPaymentSdk { iosXcodeProject = … }` at. A file you already added by hand"
            md += "is detected and left untouched, so there is nothing to do:"
        } else {
            md += "These files are generated by the SDK and MUST be members of your app target so"
            md += "they are copied into the built `.app`. They are read by bundle lookup at"
            md += "runtime, so a missing member fails at runtime, not at build time. Declare them"
            md += "as resources in your XcodeGen/Tuist spec (or set"
            md += "`lokalPaymentSdk { iosXcodeProject = … }` to have the SDK wire them for you):"
        }
        md += ""
        bundledResources.forEach { md += "- `$it`" }
    }

    val integrationFile = File(packageDir, "INTEGRATION.md")
    val changed = writeIfChanged(integrationFile, md.joinToString("\n") + "\n")
    if (changed) {
        project.logger.lifecycle("LokalPaymentSDK: iOS integration steps updated → $integrationFile")
    }
}
