package com.getlokalapp.paymentsdk.shared

import com.getlokalapp.paymentsdk.host.LokalGatewayHostContributor
import com.getlokalapp.paymentsdk.host.LokalPaymentSdkExtension
import com.getlokalapp.paymentsdk.host.HostContribution
import org.gradle.api.Plugin
import org.gradle.api.Project
import java.io.File
import java.util.ServiceLoader

/**
 * The sole iOS umbrella plugin (`com.getlokalapp.paymentsdk.lokal-payment`); it took
 * over the plain `lokal-payment` id when the CocoaPods umbrella was removed in Phase 3
 * — see docs/cocoapods-to-spm-migration-plan.md (D5). Applied to the module that
 * declares the host's `XCFramework("<name>")` and produces the umbrella framework.
 *
 * Generates `build/lokal/spmPackage/Package.swift`: a `binaryTarget` wrapping the
 * host's own XCFramework (named via [LokalPaymentSdkExtension.xcFrameworkName]),
 * plus, per [LokalGatewayHostContributor] contribution, either/both of: a
 * `.package(url:, exact:)` dependency + product reference (vendor packages, e.g.
 * razorpay-pod), and a first-party Swift `.target` whose `.swift` files are copied into
 * `Sources/<name>/` (SDK-owned source, e.g. native-iap's NativeIapBridge). A thin
 * wrapper source target ties the binary target, every vendor product, and every
 * first-party source target together into the one product the app depends on — a
 * `binaryTarget` can't declare dependencies of its own, so without this wrapper a
 * contribution would be listed but never actually linked.
 *
 * Regenerated on every Gradle sync (configuration phase, mirroring how
 * `SharedCocoapodsPlugin` regenerates the Podfile's managed regions). The app adds
 * the generated folder as a local Swift package **once**, by hand, in Xcode (File >
 * Add Package Dependencies > Add Local…): Xcode has no `pod install`-equivalent a
 * Gradle plugin can drive without editing `project.pbxproj` directly, which this SDK
 * deliberately avoids (see the plan doc's D2 rationale). Every regeneration after
 * that first manual step is picked up automatically — Xcode re-resolves a local
 * package's manifest on every build.
 */
class LokalPaymentPlugin : Plugin<Project> {

    override fun apply(project: Project) {
        val config = project.extensions.create(
            "lokalPaymentSdk",
            LokalPaymentSdkExtension::class.java,
        )

        // afterEvaluate so contributors see the host's fully-declared dependency set
        // (their import self-gate), same timing as LokalPaymentPlugin.
        project.afterEvaluate {
            val xcFrameworkName = requireNotNull(config.xcFrameworkName) {
                "Host applies 'com.getlokalapp.paymentsdk.lokal-payment' but has " +
                    "not set 'lokalPaymentSdk { xcFrameworkName = \"...\" }' — " +
                    "required to locate the assembled .xcframework this plugin wraps."
            }
            val contributions = ServiceLoader.load(
                LokalGatewayHostContributor::class.java,
                LokalGatewayHostContributor::class.java.classLoader,
            ).mapNotNull { it.contribute(project, config) }

            writePackageSwift(project, xcFrameworkName, contributions)
        }
    }

    private fun writePackageSwift(
        project: Project,
        xcFrameworkName: String,
        contributions: List<HostContribution>,
    ) {
        val packageDir = project.layout.buildDirectory.dir("lokal/spmPackage").get().asFile
        val umbrellaTargetName = "${xcFrameworkName}Umbrella"
        val sourcesDir = File(packageDir, "Sources/$umbrellaTargetName")
        sourcesDir.mkdirs()

        // A regular (non-binary) target needs at least one source file to exist;
        // this one carries no logic — its only job is to declare the dependencies
        // that tie the binary target and every vendor product into one product.
        writeIfChanged(
            File(sourcesDir, "Umbrella.swift"),
            "// GENERATED by the Lokal Payment SDK — do not edit.\n",
        )

        // Always the RELEASE XCFramework (build/XCFrameworks/release/), never debug.
        // A Package.swift binaryTarget has one static `path:` and SPM validates it while
        // resolving the package graph — before any Xcode Run Script phase runs — so there
        // is no way to swap the artifact per Debug/Release configuration at build time.
        // Instead we ship ONE release binary, exactly like a normal vendored SDK (Razorpay's
        // own Razorpay.xcframework is a single release build used in both Debug and Release
        // app builds). Config (debug/release) is orthogonal to slice (device/simulator), so
        // the release XCFramework — which still carries the ios-arm64 and ios-simulator
        // slices — links correctly in every Xcode configuration, simulator or device. The
        // only thing given up is stepping into the Kotlin SDK from an Xcode Debug build,
        // which is not part of this SDK's workflow. See docs/cocoapods-to-spm-migration-plan.md.
        val xcFrameworkDir = project.layout.buildDirectory
            .dir("XCFrameworks/release/$xcFrameworkName.xcframework").get().asFile
        val xcFrameworkRelPath = packageDir.toPath().toAbsolutePath().normalize()
            .relativize(xcFrameworkDir.toPath().toAbsolutePath().normalize())
            .toString()

        val vendorPackages = contributions.mapNotNull { it.vendorPackage }
        val sourceTargets = contributions.mapNotNull { it.sourceTarget }

        // Copy each first-party source target's .swift files into Sources/<name>/ so the
        // generated package compiles them straight into the app. The contributor already
        // materialized sourceDir (e.g. unzipped the module's iossrc Maven artifact) — see
        // SourceTarget. Each target's folder is rebuilt from scratch so a source file
        // removed upstream doesn't linger.
        sourceTargets.forEach { st ->
            val destDir = File(packageDir, "Sources/${st.name}")
            destDir.deleteRecursively()
            destDir.mkdirs()
            File(st.sourceDir).listFiles { f -> f.isFile && f.name.endsWith(".swift") }
                ?.forEach { src -> File(destDir, src.name).writeText(src.readText()) }
        }

        // Built as an explicit line list (mirroring SharedCocoapodsPlugin's Ruby
        // block generation) rather than a triple-quoted template with embedded
        // multi-line interpolation — trimIndent() can't reliably re-indent a block
        // whose own line count/content varies per host. Array literals use trailing
        // commas throughout (valid SwiftPM-manifest Swift) so per-element comma
        // bookkeeping doesn't break as vendor packages and source targets vary.
        val lines = mutableListOf(
            "// swift-tools-version:5.9",
            "// GENERATED by the Lokal Payment SDK — do not edit. Regenerated on every",
            "// Gradle sync; the app adds this folder as a local Swift package ONCE, by",
            "// hand, in Xcode (File > Add Package Dependencies > Add Local…) — see",
            "// docs/cocoapods-to-spm-migration-plan.md.",
            "import PackageDescription",
            "",
            "let package = Package(",
            "    name: \"$umbrellaTargetName\",",
            "    platforms: [.iOS(.v16)],",
            "    products: [",
            "        .library(name: \"$umbrellaTargetName\", targets: [\"$umbrellaTargetName\"]),",
            "    ],",
            "    dependencies: [",
        )
        vendorPackages.forEach { v ->
            lines += "        .package(url: \"${v.url}\", exact: \"${v.exactVersion}\"),"
        }
        lines += listOf(
            "    ],",
            "    targets: [",
            "        .binaryTarget(name: \"$xcFrameworkName\", path: \"$xcFrameworkRelPath\"),",
        )
        // First-party Swift source targets, compiled straight into the package.
        sourceTargets.forEach { st ->
            lines += "        .target("
            lines += "            name: \"${st.name}\","
            if (st.linkedFrameworks.isEmpty()) {
                lines += "            path: \"Sources/${st.name}\""
            } else {
                lines += "            path: \"Sources/${st.name}\","
                lines += "            linkerSettings: ["
                st.linkedFrameworks.forEach { fw ->
                    lines += "                .linkedFramework(\"$fw\"),"
                }
                lines += "            ]"
            }
            lines += "        ),"
        }
        lines += listOf(
            "        .target(",
            "            name: \"$umbrellaTargetName\",",
            "            dependencies: [",
            "                \"$xcFrameworkName\",",
        )
        vendorPackages.forEach { v ->
            lines += "                .product(name: \"${v.productName}\", package: \"${v.packageName}\"),"
        }
        sourceTargets.forEach { st ->
            lines += "                \"${st.name}\","
        }
        lines += listOf(
            "            ],",
            "            path: \"Sources/$umbrellaTargetName\"",
            "        ),",
            "    ]",
            ")",
        )

        writeIfChanged(File(packageDir, "Package.swift"), lines.joinToString("\n") + "\n")
    }

    private fun writeIfChanged(file: File, content: String) {
        if (!file.exists() || file.readText() != content) file.writeText(content)
    }
}
