package com.getlokalapp.paymentsdk.shared

import com.getlokalapp.paymentsdk.host.HostContribution
import org.gradle.api.Project
import java.io.File

/**
 * Generates `build/lokal/spmPackage/Package.swift` for the host: a `binaryTarget` wrapping the
 * host's own XCFramework, plus each gateway's [HostContribution] (vendor `.package(...)`
 * dependencies and first-party Swift `.target`s), all tied together under one umbrella product
 * target. Extracted from `LokalPaymentPlugin` so the plugin stays pure orchestration.
 */
internal fun writePackageSwift(
    project: Project,
    xcFrameworkName: String,
    umbrellaTargetName: String,
    contributions: List<HostContribution>,
) {
    val packageDir = project.layout.buildDirectory.dir("lokal/spmPackage").get().asFile
    val sourcesDir = File(packageDir, "Sources/$umbrellaTargetName")
    sourcesDir.mkdirs()

    // A regular (non-binary) target needs at least one source file to exist;
    // this one carries no logic — its only job is to declare the dependencies
    // that tie the binary target and every vendor product into one product.
    writeIfChanged(
        File(sourcesDir, "Umbrella.swift"),
        "// GENERATED by the Lokal Payment SDK — do not edit.\n",
    )

    // Always the RELEASE XCFramework (build/XCFrameworks/release/), never debug.
    // A Package.swift binaryTarget has one static `path:` and SPM validates it while
    // resolving the package graph — before any Xcode Run Script phase runs — so there
    // is no way to swap the artifact per Debug/Release configuration at build time.
    // Instead we ship ONE release binary, exactly like a normal vendored SDK (Razorpay's
    // own Razorpay.xcframework is a single release build used in both Debug and Release
    // app builds). Config (debug/release) is orthogonal to slice (device/simulator), so
    // the release XCFramework — which still carries the ios-arm64 and ios-simulator
    // slices — links correctly in every Xcode configuration, simulator or device. The
    // only thing given up is stepping into the Kotlin SDK from an Xcode Debug build,
    // which is not part of this SDK's workflow. See docs/cocoapods-to-spm-migration-plan.md.
    val xcFrameworkDir = project.layout.buildDirectory
        .dir("XCFrameworks/release/$xcFrameworkName.xcframework").get().asFile
    val xcFrameworkRelPath = packageDir.toPath().toAbsolutePath().normalize()
        .relativize(xcFrameworkDir.toPath().toAbsolutePath().normalize())
        .toString()

    val vendorPackages = contributions.mapNotNull { it.vendorPackage }
    val sourceTargets = contributions.mapNotNull { it.sourceTarget }

    // Copy each first-party source target's .swift files into Sources/<name>/ so the
    // generated package compiles them straight into the app. The contributor already
    // materialized sourceDir (e.g. unzipped the module's iossrc Maven artifact) — see
    // SourceTarget. Each target's folder is rebuilt from scratch so a source file
    // removed upstream doesn't linger.
    sourceTargets.forEach { st ->
        val destDir = File(packageDir, "Sources/${st.name}")
        destDir.deleteRecursively()
        destDir.mkdirs()
        File(st.sourceDir).listFiles { f -> f.isFile && f.name.endsWith(".swift") }
            ?.forEach { src -> File(destDir, src.name).writeText(src.readText()) }
    }

    // Built as an explicit line list (mirroring SharedCocoapodsPlugin's Ruby
    // block generation) rather than a triple-quoted template with embedded
    // multi-line interpolation — trimIndent() can't reliably re-indent a block
    // whose own line count/content varies per host. Array literals use trailing
    // commas throughout (valid SwiftPM-manifest Swift) so per-element comma
    // bookkeeping doesn't break as vendor packages and source targets vary.
    val lines = mutableListOf(
        "// swift-tools-version:5.9",
        "// GENERATED by the Lokal Payment SDK — do not edit. Regenerated on every",
        "// Gradle sync; the app wires this folder in as a local Swift package ONCE",
        "// (XcodeGen/Tuist spec, or Xcode 'Add Local…') — see the generated",
        "// INTEGRATION.md beside this file, or docs/integrating-the-sdk.md.",
        "import PackageDescription",
        "",
        "let package = Package(",
        "    name: \"$umbrellaTargetName\",",
        "    platforms: [.iOS(.v16)],",
        "    products: [",
        "        .library(name: \"$umbrellaTargetName\", targets: [\"$umbrellaTargetName\"]),",
        "    ],",
        "    dependencies: [",
    )
    vendorPackages.forEach { v ->
        lines += "        .package(url: \"${v.url}\", exact: \"${v.exactVersion}\"),"
    }
    lines += listOf(
        "    ],",
        "    targets: [",
        "        .binaryTarget(name: \"$xcFrameworkName\", path: \"$xcFrameworkRelPath\"),",
    )
    // First-party Swift source targets, compiled straight into the package.
    sourceTargets.forEach { st ->
        lines += "        .target("
        lines += "            name: \"${st.name}\","
        if (st.linkedFrameworks.isEmpty()) {
            lines += "            path: \"Sources/${st.name}\""
        } else {
            lines += "            path: \"Sources/${st.name}\","
            lines += "            linkerSettings: ["
            st.linkedFrameworks.forEach { fw ->
                lines += "                .linkedFramework(\"$fw\"),"
            }
            lines += "            ]"
        }
        lines += "        ),"
    }
    lines += listOf(
        "        .target(",
        "            name: \"$umbrellaTargetName\",",
        "            dependencies: [",
        "                \"$xcFrameworkName\",",
    )
    vendorPackages.forEach { v ->
        lines += "                .product(name: \"${v.productName}\", package: \"${v.packageName}\"),"
    }
    sourceTargets.forEach { st ->
        lines += "                \"${st.name}\","
    }
    lines += listOf(
        "            ],",
        "            path: \"Sources/$umbrellaTargetName\"",
        "        ),",
        "    ]",
        ")",
    )

    writeIfChanged(File(packageDir, "Package.swift"), lines.joinToString("\n") + "\n")
}
