package com.getlokalapp.paymentsdk.shared

import com.getlokalapp.paymentsdk.host.HostContribution
import com.getlokalapp.paymentsdk.host.PrebuildStep
import org.gradle.api.Project
import java.io.File

/**
 * Materializes [coreSteps] plus every gateway's [HostContribution.prebuildStep] into
 * `prebuild.d/<name>.sh` beside a generated `lokal-prebuild.sh` dispatcher, and returns the
 * dispatcher (or null if there is nothing to run). The app registers the dispatcher as one
 * Xcode scheme pre-build action; it runs each snippet in sorted order under `set -eu`, failing
 * the build loudly if any step fails. The SPM reincarnation of the CocoaPods managed
 * `post_install` dispatch. The `prebuild.d` dir is rebuilt from scratch each sync so a gateway
 * that was removed doesn't leave a stale snippet behind.
 *
 * [coreSteps] are the SDK's own, gateway-independent steps (currently the per-configuration
 * Kotlin XCFramework restage — see [kotlinXCFrameworkPrebuildStep]). They ride the same
 * dispatcher a host has already registered, so adding one costs the host no new wiring.
 */
internal fun writePrebuildDispatcher(
    project: Project,
    coreSteps: List<PrebuildStep>,
    contributions: List<HostContribution>,
): File? {
    val packageDir = project.layout.buildDirectory.dir("lokal/spmPackage").get().asFile
    val stepsDir = File(packageDir, "prebuild.d")
    val dispatcher = File(packageDir, "lokal-prebuild.sh")
    val steps = coreSteps + contributions.mapNotNull { it.prebuildStep }

    stepsDir.deleteRecursively()
    if (steps.isEmpty()) {
        dispatcher.delete()
        return null
    }
    stepsDir.mkdirs()
    steps.forEach { step ->
        File(stepsDir, "${step.name}.sh").apply {
            writeText("#!/bin/sh\n" + step.script.trimEnd('\n') + "\n")
            setExecutable(true)
        }
    }
    dispatcher.writeText(PREBUILD_DISPATCHER)
    dispatcher.setExecutable(true)
    return dispatcher
}

/**
 * The generated pre-build dispatcher. Host-independent (locates its own snippet dir via
 * `dirname "$0"`), so it's a constant rather than per-host template. Runs every `.sh`
 * snippet in `prebuild.d` in sorted order; `set -eu` makes any failing step fail the build.
 */
private val PREBUILD_DISPATCHER = """
    #!/bin/sh
    # GENERATED by the Lokal Payment SDK — do not edit. Regenerated on every Gradle sync.
    #
    # One Xcode scheme pre-build action for every gateway's iOS build-time setup. Add
    # this script ONCE as a scheme pre-build action, with "Provide build settings from
    # <your app target>" enabled so build settings (${'$'}BUILD_DIR, ${'$'}SRCROOT, …) are in
    # scope. Each gateway that needs build-time work drops a snippet in prebuild.d/; this
    # runs them all, in order, and fails the build loudly if any step fails.
    set -eu
    steps_dir="${'$'}(CDPATH= cd -- "${'$'}(dirname -- "${'$'}0")" && pwd)/prebuild.d"
    [ -d "${'$'}steps_dir" ] || exit 0
    for step in "${'$'}steps_dir"/*.sh; do
      [ -e "${'$'}step" ] || continue
      echo "Lokal Payment SDK: prebuild step ${'$'}(basename -- "${'$'}step")"
      sh "${'$'}step"
    done
""".trimIndent() + "\n"
